version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            POSTGRES_DB: 'postgres'
            POSTGRES_HOST_AUTH_METHOD: 'trust'
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    api:
        build:
            dockerfile: Dockerfile.dev
            # context shows where to look for the dockerfile / source code
            context: ./server
        volumes:
            # don't override the node_modeules
            - /app/node_modules
            # redirect volume: /app specified in deockerfile for container. So redirect server to app
            # therefore anything changed in server folder will auto update to app folder in container
            # so we don't need to rebuild image every time
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on:
            - postgres
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
